platform :osx, '10.10'

target 'wifi-password-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wifi-password-app
  pod 'SAMKeychain'

end
